language: go

go:
  - master

sudo: required

go_import_path: github.com/ling7334/glog

install:
  - export GOPATH=$HOME/gopath/src/github.com/ling7334/glog
  - export PATH=$PATH:$HOME/gopath/src/github.com/ling7334/glog/bin
  - go get -v github.com/ling7334/glog

script:
  - go test -v -coverprofile=coverage.txt

after_script:
  - bash <(curl -s https://codecov.io/bash)
